// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package banyan

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Condition struct {
	_tab flatbuffers.Table
}

func GetRootAsCondition(buf []byte, offset flatbuffers.UOffsetT) *Condition {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Condition{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsCondition(buf []byte, offset flatbuffers.UOffsetT) *Condition {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Condition{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Condition) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Condition) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Condition) Logic() Logic {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return Logic(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Condition) MutateLogic(n Logic) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func (rcv *Condition) Expression(obj *ConditionExpression, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Condition) ExpressionLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func ConditionStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ConditionAddLogic(builder *flatbuffers.Builder, logic Logic) {
	builder.PrependInt8Slot(0, int8(logic), 0)
}
func ConditionAddExpression(builder *flatbuffers.Builder, expression flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(expression), 0)
}
func ConditionStartExpressionVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ConditionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
