// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package banyan

import "strconv"

type DataType byte

const (
	DataTypeNONE        DataType = 0
	DataTypeString      DataType = 1
	DataTypeUinteger    DataType = 2
	DataTypeBoolean     DataType = 3
	DataTypeStringArray DataType = 4
	DataTypeTags        DataType = 5
)

var EnumNamesDataType = map[DataType]string{
	DataTypeNONE:        "NONE",
	DataTypeString:      "String",
	DataTypeUinteger:    "Uinteger",
	DataTypeBoolean:     "Boolean",
	DataTypeStringArray: "StringArray",
	DataTypeTags:        "Tags",
}

var EnumValuesDataType = map[string]DataType{
	"NONE":        DataTypeNONE,
	"String":      DataTypeString,
	"Uinteger":    DataTypeUinteger,
	"Boolean":     DataTypeBoolean,
	"StringArray": DataTypeStringArray,
	"Tags":        DataTypeTags,
}

func (v DataType) String() string {
	if s, ok := EnumNamesDataType[v]; ok {
		return s
	}
	return "DataType(" + strconv.FormatInt(int64(v), 10) + ")"
}
