// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package banyan

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Integer struct {
	_tab flatbuffers.Table
}

func GetRootAsInteger(buf []byte, offset flatbuffers.UOffsetT) *Integer {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Integer{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsInteger(buf []byte, offset flatbuffers.UOffsetT) *Integer {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Integer{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Integer) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Integer) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Integer) Value() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Integer) MutateValue(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func IntegerStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func IntegerAddValue(builder *flatbuffers.Builder, value int32) {
	builder.PrependInt32Slot(0, value, 0)
}
func IntegerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
