// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package banyan

import "strconv"

type Logic int8

const (
	LogicOR  Logic = 0
	LogicAND Logic = 1
)

var EnumNamesLogic = map[Logic]string{
	LogicOR:  "OR",
	LogicAND: "AND",
}

var EnumValuesLogic = map[string]Logic{
	"OR":  LogicOR,
	"AND": LogicAND,
}

func (v Logic) String() string {
	if s, ok := EnumNamesLogic[v]; ok {
		return s
	}
	return "Logic(" + strconv.FormatInt(int64(v), 10) + ")"
}
