// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package banyan

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Long struct {
	_tab flatbuffers.Table
}

func GetRootAsLong(buf []byte, offset flatbuffers.UOffsetT) *Long {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Long{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsLong(buf []byte, offset flatbuffers.UOffsetT) *Long {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Long{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Long) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Long) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Long) Value() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Long) MutateValue(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func LongStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func LongAddValue(builder *flatbuffers.Builder, value int64) {
	builder.PrependInt64Slot(0, value, 0)
}
func LongEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
