// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package banyan

import "strconv"

type Operator int8

const (
	OperatorEquals     Operator = 0
	OperatorBetween    Operator = 1
	OperatorWithPrefix Operator = 2
)

var EnumNamesOperator = map[Operator]string{
	OperatorEquals:     "Equals",
	OperatorBetween:    "Between",
	OperatorWithPrefix: "WithPrefix",
}

var EnumValuesOperator = map[string]Operator{
	"Equals":     OperatorEquals,
	"Between":    OperatorBetween,
	"WithPrefix": OperatorWithPrefix,
}

func (v Operator) String() string {
	if s, ok := EnumNamesOperator[v]; ok {
		return s
	}
	return "Operator(" + strconv.FormatInt(int64(v), 10) + ")"
}
