// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package banyan

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SelectRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsSelectRequest(buf []byte, offset flatbuffers.UOffsetT) *SelectRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SelectRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsSelectRequest(buf []byte, offset flatbuffers.UOffsetT) *SelectRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SelectRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *SelectRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SelectRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SelectRequest) Queryfileds(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *SelectRequest) QueryfiledsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *SelectRequest) Conditions(obj *Condition, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *SelectRequest) ConditionsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func SelectRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SelectRequestAddQueryfileds(builder *flatbuffers.Builder, queryfileds flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(queryfileds), 0)
}
func SelectRequestStartQueryfiledsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func SelectRequestAddConditions(builder *flatbuffers.Builder, conditions flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(conditions), 0)
}
func SelectRequestStartConditionsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func SelectRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
