// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package banyan

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SelectResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsSelectResponse(buf []byte, offset flatbuffers.UOffsetT) *SelectResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SelectResponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsSelectResponse(buf []byte, offset flatbuffers.UOffsetT) *SelectResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SelectResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *SelectResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SelectResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SelectResponse) Mappings(obj *FieldMapping, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *SelectResponse) MappingsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func SelectResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SelectResponseAddMappings(builder *flatbuffers.Builder, mappings flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(mappings), 0)
}
func SelectResponseStartMappingsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func SelectResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
