// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package banyan

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type WriteResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsWriteResponse(buf []byte, offset flatbuffers.UOffsetT) *WriteResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &WriteResponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsWriteResponse(buf []byte, offset flatbuffers.UOffsetT) *WriteResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &WriteResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *WriteResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *WriteResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func WriteResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func WriteResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
